# Generated by Django 4.2.5 on 2024-08-10 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_profile_subscribed_plan_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="subscribed_plan",),
        migrations.RemoveField(model_name="profile", name="subscription_expiry_date",),
    ]
