# Generated by Django 4.2.5 on 2023-11-27 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeneratedResume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=100)),
                ("job_description", models.TextField(null=True)),
                ("existing_resume", models.TextField(null=True)),
                ("generated_text", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedCoverLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_text", models.TextField()),
                (
                    "generated_resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resume.generatedresume",
                    ),
                ),
            ],
        ),
    ]
